// <auto-generated />
using System;
using AiTutor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiTutor.Infrastructure.Migrations
{
    [DbContext(typeof(AiTutorDbContext))]
    [Migration("20260508060543_AddTableAndColumnComments")]
    partial class AddTableAndColumnComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AiTutor.Core.Entities.AgentRouteLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<string>("InputType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Agent 输入类型。");

                    b.Property<string>("QuestionMode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("路由识别的提问模式。");

                    b.Property<string>("QuestionRecordId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("提问记录 Id，关联 QuestionRecord.Id。");

                    b.Property<string>("RouteReason")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("路由原因。");

                    b.Property<string>("SelectedAgent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("路由选中的 Agent。");

                    b.Property<string>("SelectedModelName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("路由选中的模型名称。");

                    b.Property<string>("SelectedModelProvider")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("路由选中的模型提供方。");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("学习会话 Id，关联 LearningSession.Id。");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("用户 Id，关联 UserProfile.Id。");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("QuestionRecordId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("AgentRouteLog", null, t =>
                        {
                            t.HasComment("Agent 路由日志表，记录每次请求选择的 Agent、模型和路由原因。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.AnswerRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<string>("AgentName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Agent 名称。");

                    b.Property<string>("AnswerJson")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("AI 回答结构化 JSON。");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("AI 回答文本。");

                    b.Property<string>("AudioPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("音频文件路径。");

                    b.Property<string>("AvatarScriptJson")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("数字人脚本 JSON。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<string>("ModelName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("模型名称。");

                    b.Property<string>("OutputType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("输出类型。");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Prompt 版本。");

                    b.Property<string>("QuestionRecordId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("提问记录 Id，关联 QuestionRecord.Id。");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("用户 Id，关联 UserProfile.Id。");

                    b.Property<string>("VideoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("视频文件路径。");

                    b.HasKey("Id");

                    b.HasIndex("QuestionRecordId");

                    b.HasIndex("UserId");

                    b.ToTable("AnswerRecord", null, t =>
                        {
                            t.HasComment("回答记录表，保存 AI 回答文本、结构化结果、模型、Agent 和多媒体输出。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.HomeworkCheckItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("正确答案。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<string>("ErrorReason")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("错误原因。");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("讲解内容。");

                    b.Property<string>("Grade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("年级。");

                    b.Property<string>("ImageCropPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("题目截图裁剪路径。");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit")
                        .HasComment("是否正确。");

                    b.Property<string>("KnowledgePointId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("知识点 Id，关联 KnowledgePoint.Id。");

                    b.Property<string>("QuestionNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("题号。");

                    b.Property<string>("QuestionRecordId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("提问记录 Id，关联 QuestionRecord.Id。");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("题目或问题文本。");

                    b.Property<string>("StudentAnswer")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("学生答案。");

                    b.Property<string>("Subject")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("学科。");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后更新时间，未更新时为空。");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("用户 Id，关联 UserProfile.Id。");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgePointId");

                    b.HasIndex("QuestionRecordId");

                    b.HasIndex("UserId");

                    b.ToTable("HomeworkCheckItem", null, t =>
                        {
                            t.HasComment("作业检查明细表，保存一张作业图片拆出的单题检查结果。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.KnowledgeChunk", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("知识片段正文。");

                    b.Property<string>("ChunkTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("知识片段标题。");

                    b.Property<string>("ChunkType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("知识片段类型。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<string>("KnowledgePointId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("知识点 Id，关联 KnowledgePoint.Id。");

                    b.Property<string>("LessonId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("课时或章节 Id，关联 Lesson.Id。");

                    b.Property<string>("PageId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("教材页 Id，关联 TextbookPage.Id。");

                    b.Property<int?>("PageNo")
                        .HasColumnType("int")
                        .HasComment("页码。");

                    b.Property<int>("SortIndex")
                        .HasColumnType("int")
                        .HasComment("排序值，数值越小越靠前。");

                    b.Property<string>("SourcePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("来源文件或资源路径。");

                    b.Property<string>("SourceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("来源类型。");

                    b.Property<string>("TextbookId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("教材 Id，关联 Textbook.Id。");

                    b.Property<string>("UnitId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("教材单元 Id，关联 TextbookUnit.Id。");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后更新时间，未更新时为空。");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgePointId");

                    b.HasIndex("TextbookId");

                    b.ToTable("KnowledgeChunk", null, t =>
                        {
                            t.HasComment("知识片段表，保存教材切片文本及其来源、页码和知识点关联。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.KnowledgeEmbedding", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<string>("ChunkId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("知识片段 Id，关联 KnowledgeChunk.Id。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("生成向量的模型名称。");

                    b.Property<string>("VectorData")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("向量数据预留字段，第一阶段以文本形式保存。");

                    b.Property<string>("VectorHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("向量数据哈希。");

                    b.HasKey("Id");

                    b.HasIndex("ChunkId");

                    b.ToTable("KnowledgeEmbedding", null, t =>
                        {
                            t.HasComment("知识向量表，预留向量检索模型、向量数据和哈希信息。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.KnowledgePoint", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("详细说明。");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int")
                        .HasComment("难度等级，默认 1。");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("年级。");

                    b.Property<string>("LessonId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("课时或章节 Id，关联 Lesson.Id。");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("名称。");

                    b.Property<string>("PageId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("教材页 Id，关联 TextbookPage.Id。");

                    b.Property<string>("ParentId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("父级 Id，用于树形层级。");

                    b.Property<string>("PointType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("知识点类型。");

                    b.Property<int>("SortIndex")
                        .HasColumnType("int")
                        .HasComment("排序值，数值越小越靠前。");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("学科。");

                    b.Property<string>("TextbookId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("教材 Id，关联 Textbook.Id。");

                    b.Property<string>("UnitId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("教材单元 Id，关联 TextbookUnit.Id。");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后更新时间，未更新时为空。");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("TextbookId");

                    b.HasIndex("Subject", "Grade");

                    b.ToTable("KnowledgePoint", null, t =>
                        {
                            t.HasComment("知识点表，保存学科年级下的知识点、层级关系和难度信息。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.LearningProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<string>("DefaultSubject")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("默认学习学科。");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("年级。");

                    b.Property<string>("SchoolName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("学校名称。");

                    b.Property<string>("Semester")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("学期或册别，例如上册、下册。");

                    b.Property<string>("TextbookVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("默认教材版本。");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后更新时间，未更新时为空。");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("用户 Id，关联 UserProfile.Id。");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LearningProfile", null, t =>
                        {
                            t.HasComment("学生学习档案表，保存年级、学期、学校、默认学科和教材版本等学习画像。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.LearningSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2")
                        .HasComment("会话结束时间。");

                    b.Property<string>("Grade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("年级。");

                    b.Property<string>("RelatedQuestionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("关联问题 Id。");

                    b.Property<string>("RelatedWrongId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("关联错题 Id。");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("学习会话类型。");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasComment("会话开始时间。");

                    b.Property<string>("Subject")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("学科。");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("摘要。");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("标题。");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后更新时间，未更新时为空。");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("用户 Id，关联 UserProfile.Id。");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedTime");

                    b.ToTable("LearningSession", null, t =>
                        {
                            t.HasComment("学习会话表，记录一次问答、拍照讲题、作业检查或复习过程。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.Lesson", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<int?>("LessonNo")
                        .HasColumnType("int")
                        .HasComment("课时或章节序号。");

                    b.Property<int?>("PageEnd")
                        .HasColumnType("int")
                        .HasComment("结束页码。");

                    b.Property<int?>("PageStart")
                        .HasColumnType("int")
                        .HasComment("起始页码。");

                    b.Property<int>("SortIndex")
                        .HasColumnType("int")
                        .HasComment("排序值，数值越小越靠前。");

                    b.Property<string>("TextbookId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("教材 Id，关联 Textbook.Id。");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("标题。");

                    b.Property<string>("UnitId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("教材单元 Id，关联 TextbookUnit.Id。");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后更新时间，未更新时为空。");

                    b.HasKey("Id");

                    b.HasIndex("TextbookId");

                    b.HasIndex("UnitId");

                    b.ToTable("Lesson", null, t =>
                        {
                            t.HasComment("教材课时或章节表，保存课题、页码范围和所属单元。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.MediaResource", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("int")
                        .HasComment("媒体时长，单位毫秒。");

                    b.Property<string>("FileName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("文件名。");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("文件路径。");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasComment("文件大小，单位字节。");

                    b.Property<string>("Hash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("文件或内容哈希。");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasComment("图片或视频高度。");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("MIME 类型。");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("媒体资源类型。");

                    b.Property<string>("SourceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("来源类型。");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后更新时间，未更新时为空。");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("用户 Id，关联 UserProfile.Id。");

                    b.Property<int?>("Width")
                        .HasColumnType("int")
                        .HasComment("图片或视频宽度。");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ResourceType");

                    b.ToTable("MediaResource", null, t =>
                        {
                            t.HasComment("媒体资源表，统一管理图片、音频、视频、PDF、裁剪图和数字人脚本资源。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.ModelCallLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<string>("AgentName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Agent 名称。");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,4)")
                        .HasComment("模型调用成本。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("int")
                        .HasComment("媒体时长，单位毫秒。");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("错误消息。");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("int")
                        .HasComment("输入 Token 数。");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit")
                        .HasComment("模型调用是否成功。");

                    b.Property<string>("ModelName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("模型名称。");

                    b.Property<string>("ModelProvider")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("模型提供方。");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("int")
                        .HasComment("输出 Token 数。");

                    b.Property<string>("PromptText")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("发送给模型的 Prompt 文本。");

                    b.Property<string>("QuestionRecordId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("提问记录 Id，关联 QuestionRecord.Id。");

                    b.Property<string>("RequestType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("请求类型。");

                    b.Property<string>("ResponseText")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("模型返回文本。");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("学习会话 Id，关联 LearningSession.Id。");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("用户 Id，关联 UserProfile.Id。");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("QuestionRecordId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("ModelCallLog", null, t =>
                        {
                            t.HasComment("模型调用日志表，记录每次模型调用的输入输出、Token、耗时、成本和错误。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.PracticeAnswerRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<string>("AiFeedback")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("AI 反馈。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int")
                        .HasComment("耗时，单位秒。");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit")
                        .HasComment("是否正确。");

                    b.Property<string>("PracticeQuestionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("练习题 Id，关联 PracticeQuestion.Id。");

                    b.Property<string>("UserAnswer")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("用户作答内容。");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("用户 Id，关联 UserProfile.Id。");

                    b.HasKey("Id");

                    b.HasIndex("PracticeQuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("PracticeAnswerRecord", null, t =>
                        {
                            t.HasComment("练习作答记录表，保存学生练习题作答结果、反馈和耗时。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.PracticeQuestion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("正确答案。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int")
                        .HasComment("难度等级，默认 1。");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("讲解内容。");

                    b.Property<string>("GenerateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("练习题生成类型。");

                    b.Property<string>("Grade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("年级。");

                    b.Property<string>("KnowledgePointId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("知识点 Id，关联 KnowledgePoint.Id。");

                    b.Property<string>("ModelName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("模型名称。");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Prompt 版本。");

                    b.Property<string>("QuestionImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("题目图片路径。");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("题目或问题文本。");

                    b.Property<string>("SourceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("来源类型。");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("学科。");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后更新时间，未更新时为空。");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("用户 Id，关联 UserProfile.Id。");

                    b.Property<string>("WrongQuestionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("错题 Id，关联 WrongQuestion.Id。");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgePointId");

                    b.HasIndex("UserId");

                    b.HasIndex("WrongQuestionId");

                    b.ToTable("PracticeQuestion", null, t =>
                        {
                            t.HasComment("练习题表，保存由错题、知识点、阶段任务或人工生成的练习题。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.PracticeQuestionSource", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<string>("PracticeQuestionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("练习题 Id，关联 PracticeQuestion.Id。");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("练习题来源表，记录练习题与错题、知识点、教材切片等来源的关系。字段 SourceId。");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("来源类型。");

                    b.HasKey("Id");

                    b.HasIndex("PracticeQuestionId");

                    b.ToTable("PracticeQuestionSource", null, t =>
                        {
                            t.HasComment("练习题来源表，记录练习题与错题、知识点、教材切片等来源的关系。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.QuestionRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<string>("AudioPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("音频文件路径。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<string>("Grade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("年级。");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("图片文件路径。");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Agent 输入类型。");

                    b.Property<string>("Mode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("提问模式。");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("题目或问题文本。");

                    b.Property<string>("RecognizedText")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("从图片或音频识别出的文本。");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("学习会话 Id，关联 LearningSession.Id。");

                    b.Property<string>("SourceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("来源类型。");

                    b.Property<string>("Subject")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("学科。");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后更新时间，未更新时为空。");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("用户 Id，关联 UserProfile.Id。");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId", "CreatedTime");

                    b.ToTable("QuestionRecord", null, t =>
                        {
                            t.HasComment("提问记录表，保存学生输入的问题文本、图片、音频、识别文本和提问模式。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.ReviewSchedule", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<string>("Grade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("年级。");

                    b.Property<string>("KnowledgePointId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("知识点 Id，关联 KnowledgePoint.Id。");

                    b.Property<DateTime?>("LastReviewTime")
                        .HasColumnType("datetime2")
                        .HasComment("上次复习时间。");

                    b.Property<DateTime>("NextReviewTime")
                        .HasColumnType("datetime2")
                        .HasComment("下次复习时间。");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int")
                        .HasComment("复习次数。");

                    b.Property<int>("ReviewLevel")
                        .HasColumnType("int")
                        .HasComment("复习等级。");

                    b.Property<string>("ReviewTargetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("复习目标 Id。");

                    b.Property<string>("ReviewTargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("复习目标类型。");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("状态。");

                    b.Property<string>("Subject")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("学科。");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后更新时间，未更新时为空。");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("用户 Id，关联 UserProfile.Id。");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgePointId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId", "NextReviewTime");

                    b.ToTable("ReviewSchedule", null, t =>
                        {
                            t.HasComment("复习计划表，保存错题、知识点或练习题的下次复习安排。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.SessionMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<string>("AudioPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("音频文件路径。");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("消息内容类型。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("图片文件路径。");

                    b.Property<string>("MessageJson")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("消息结构化 JSON。");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("消息角色。");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("学习会话 Id，关联 LearningSession.Id。");

                    b.Property<string>("TextContent")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("文本内容。");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("用户 Id，关联 UserProfile.Id。");

                    b.Property<string>("VideoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("视频文件路径。");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SessionId", "CreatedTime");

                    b.ToTable("SessionMessage", null, t =>
                        {
                            t.HasComment("会话消息表，记录学习会话中的文本、图片、音频、视频和数字人脚本消息。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.StageTask", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("详细说明。");

                    b.Property<string>("RelatedKnowledgePointId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("关联知识点 Id。");

                    b.Property<string>("RelatedPracticeQuestionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("关联练习题 Id。");

                    b.Property<string>("RelatedWrongQuestionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("关联错题 Id。");

                    b.Property<int>("SortIndex")
                        .HasColumnType("int")
                        .HasComment("排序值，数值越小越靠前。");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("状态。");

                    b.Property<string>("StudyStageId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("学习阶段 Id，关联 StudyStage.Id。");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("阶段任务类型。");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("标题。");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后更新时间，未更新时为空。");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("用户 Id，关联 UserProfile.Id。");

                    b.HasKey("Id");

                    b.HasIndex("RelatedKnowledgePointId");

                    b.HasIndex("RelatedPracticeQuestionId");

                    b.HasIndex("RelatedWrongQuestionId");

                    b.HasIndex("UserId");

                    b.HasIndex("StudyStageId", "Status");

                    b.ToTable("StageTask", null, t =>
                        {
                            t.HasComment("阶段任务表，保存每个学习阶段中的讲解、练习、复习、语音讨论或视频任务。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.StageTaskRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("动作类型。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int")
                        .HasComment("耗时，单位秒。");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注。");

                    b.Property<string>("Result")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("执行结果。");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5,2)")
                        .HasComment("得分。");

                    b.Property<string>("StageTaskId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("阶段任务 Id，关联 StageTask.Id。");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("用户 Id，关联 UserProfile.Id。");

                    b.HasKey("Id");

                    b.HasIndex("StageTaskId");

                    b.HasIndex("UserId");

                    b.ToTable("StageTaskRecord", null, t =>
                        {
                            t.HasComment("阶段任务记录表，保存学生完成阶段任务时的动作、结果、得分和备注。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.StudyPlan", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasComment("结束日期。");

                    b.Property<string>("Grade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("年级。");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("学习计划类型。");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasComment("开始日期。");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("状态。");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("学科。");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("摘要。");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("标题。");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后更新时间，未更新时为空。");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("用户 Id，关联 UserProfile.Id。");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("StudyPlan", null, t =>
                        {
                            t.HasComment("学习计划表，保存面向知识点、错题或考试准备的阶段化学习计划。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.StudyStage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasComment("结束日期。");

                    b.Property<string>("Goal")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("阶段目标。");

                    b.Property<int>("StageNo")
                        .HasColumnType("int")
                        .HasComment("阶段序号。");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasComment("开始日期。");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("状态。");

                    b.Property<string>("StudyPlanId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("学习计划 Id，关联 StudyPlan.Id。");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("标题。");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后更新时间，未更新时为空。");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("StudyPlanId");

                    b.ToTable("StudyStage", null, t =>
                        {
                            t.HasComment("学习阶段表，保存学习计划拆分出的阶段目标、状态和时间。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.Textbook", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<string>("CoverImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("封面图片路径。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("详细说明。");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("年级。");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("名称。");

                    b.Property<string>("Publisher")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("出版社。");

                    b.Property<string>("Semester")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("学期或册别，例如上册、下册。");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("学科。");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后更新时间，未更新时为空。");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("版本号或版本描述。");

                    b.HasKey("Id");

                    b.HasIndex("Subject", "Grade");

                    b.ToTable("Textbook", null, t =>
                        {
                            t.HasComment("教材主表，保存教材名称、出版社、学科、年级、册别、版本和封面信息。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.TextbookImportFile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("文件名。");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("文件路径。");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasComment("文件大小，单位字节。");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("文件类型。");

                    b.Property<string>("Hash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("文件或内容哈希。");

                    b.Property<string>("ImportJobId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("教材导入任务 Id，关联 TextbookImportJob.Id。");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("MIME 类型。");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int")
                        .HasComment("文件页数。");

                    b.Property<string>("TextbookId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("教材 Id，关联 Textbook.Id。");

                    b.HasKey("Id");

                    b.HasIndex("ImportJobId");

                    b.HasIndex("TextbookId");

                    b.ToTable("TextbookImportFile", null, t =>
                        {
                            t.HasComment("教材导入文件表，记录导入任务关联的 PDF、图片等源文件信息。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.TextbookImportJob", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("错误消息。");

                    b.Property<DateTime?>("FinishedTime")
                        .HasColumnType("datetime2")
                        .HasComment("任务完成时间。");

                    b.Property<string>("ImportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("教材导入类型。");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("导入任务名称。");

                    b.Property<int?>("ParsedPages")
                        .HasColumnType("int")
                        .HasComment("已解析页数。");

                    b.Property<string>("SourceFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("源文件路径。");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("状态。");

                    b.Property<string>("TextbookId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("教材 Id，关联 Textbook.Id。");

                    b.Property<int?>("TotalChunks")
                        .HasColumnType("int")
                        .HasComment("生成的知识片段总数。");

                    b.Property<int?>("TotalPages")
                        .HasColumnType("int")
                        .HasComment("总页数。");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后更新时间，未更新时为空。");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("用户 Id，关联 UserProfile.Id。");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TextbookId");

                    b.HasIndex("UserId");

                    b.ToTable("TextbookImportJob", null, t =>
                        {
                            t.HasComment("教材导入任务表，记录教材上传、解析、OCR、切片和向量化流程状态。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.TextbookPage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<string>("CleanText")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("清洗后的文本。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("图片文件路径。");

                    b.Property<string>("LessonId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("课时或章节 Id，关联 Lesson.Id。");

                    b.Property<string>("OcrText")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("OCR 识别原文。");

                    b.Property<int>("PageNo")
                        .HasColumnType("int")
                        .HasComment("页码。");

                    b.Property<string>("PdfPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("PDF 文件路径。");

                    b.Property<string>("TextbookId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("教材 Id，关联 Textbook.Id。");

                    b.Property<string>("UnitId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("教材单元 Id，关联 TextbookUnit.Id。");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后更新时间，未更新时为空。");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UnitId");

                    b.HasIndex("TextbookId", "PageNo");

                    b.ToTable("TextbookPage", null, t =>
                        {
                            t.HasComment("教材页表，保存教材页面图片、PDF 路径、OCR 原文和清洗文本。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.TextbookParseLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("错误详细信息。");

                    b.Property<string>("ImportJobId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("教材导入任务 Id，关联 TextbookImportJob.Id。");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("日志消息。");

                    b.Property<int?>("PageNo")
                        .HasColumnType("int")
                        .HasComment("页码。");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("状态。");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("处理步骤名称。");

                    b.Property<string>("TextbookId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("教材 Id，关联 Textbook.Id。");

                    b.HasKey("Id");

                    b.HasIndex("ImportJobId");

                    b.HasIndex("Status");

                    b.HasIndex("TextbookId");

                    b.ToTable("TextbookParseLog", null, t =>
                        {
                            t.HasComment("教材解析日志表，记录教材导入过程中的步骤、状态、消息和错误详情。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.TextbookUnit", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("详细说明。");

                    b.Property<int>("SortIndex")
                        .HasColumnType("int")
                        .HasComment("排序值，数值越小越靠前。");

                    b.Property<string>("TextbookId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("教材 Id，关联 Textbook.Id。");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("标题。");

                    b.Property<int>("UnitNo")
                        .HasColumnType("int")
                        .HasComment("单元序号。");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后更新时间，未更新时为空。");

                    b.HasKey("Id");

                    b.HasIndex("TextbookId");

                    b.ToTable("TextbookUnit", null, t =>
                        {
                            t.HasComment("教材单元表，按教材组织单元目录和排序信息。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.UserProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<string>("AvatarPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("用户头像文件路径。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("用户显示名称。");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("手机号，第一阶段可为空。");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后更新时间，未更新时为空。");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("用户类型，例如 student、parent 或 admin。");

                    b.HasKey("Id");

                    b.ToTable("UserProfile", null, t =>
                        {
                            t.HasComment("用户基础信息表，保存学生、家长或维护人员的基础身份信息。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.WrongQuestion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("正确答案。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int")
                        .HasComment("难度等级，默认 1。");

                    b.Property<string>("ErrorReason")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("错误原因。");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("讲解内容。");

                    b.Property<string>("Grade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("年级。");

                    b.Property<string>("HomeworkCheckItemId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("作业检查明细 Id，关联 HomeworkCheckItem.Id。");

                    b.Property<string>("KnowledgePointId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("知识点 Id，关联 KnowledgePoint.Id。");

                    b.Property<DateTime?>("LastReviewTime")
                        .HasColumnType("datetime2")
                        .HasComment("上次复习时间。");

                    b.Property<string>("MasteryStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("掌握状态。");

                    b.Property<DateTime?>("NextReviewTime")
                        .HasColumnType("datetime2")
                        .HasComment("下次复习时间。");

                    b.Property<string>("QuestionImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("题目图片路径。");

                    b.Property<string>("QuestionRecordId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("提问记录 Id，关联 QuestionRecord.Id。");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("题目或问题文本。");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int")
                        .HasComment("复习次数。");

                    b.Property<string>("StudentAnswer")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("学生答案。");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("学科。");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后更新时间，未更新时为空。");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("用户 Id，关联 UserProfile.Id。");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgePointId");

                    b.HasIndex("MasteryStatus");

                    b.HasIndex("NextReviewTime");

                    b.HasIndex("QuestionRecordId");

                    b.HasIndex("UserId", "Subject");

                    b.ToTable("WrongQuestion", null, t =>
                        {
                            t.HasComment("错题表，保存错题原题、答案、错因、讲解、掌握状态和复习时间。");
                        });
                });

            modelBuilder.Entity("AiTutor.Core.Entities.WrongQuestionReview", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主键，使用 32 位无分隔符 Guid 字符串。");

                    b.Property<string>("AiFeedback")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("AI 反馈。");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间，使用 UTC 时间记录。");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit")
                        .HasComment("是否正确。");

                    b.Property<int?>("ReviewDurationSec")
                        .HasColumnType("int")
                        .HasComment("复习耗时，单位秒。");

                    b.Property<string>("ReviewType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("复习类型。");

                    b.Property<string>("UserAnswer")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("用户作答内容。");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("用户 Id，关联 UserProfile.Id。");

                    b.Property<string>("WrongQuestionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("错题 Id，关联 WrongQuestion.Id。");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WrongQuestionId");

                    b.ToTable("WrongQuestionReview", null, t =>
                        {
                            t.HasComment("错题复习记录表，保存学生复习错题时的作答、反馈和耗时。");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
